export const MENU_CODES = {
  LANDLORD_DASHBOARD: 'LANDLORD_DASHBOARD',
  LANDLORD_PROPERTIES: 'LANDLORD_PROPERTIES',
  LANDLORD_TENANTS: 'LANDLORD_TENANTS',
  LANDLORD_LEASES: 'LANDLORD_LEASES',
  LANDLORD_PAYMENTS: 'LANDLORD_PAYMENTS',
  LANDLORD_ADDONS: 'LANDLORD_ADDONS',
  LANDLORD_UTILITIES: 'LANDLORD_UTILITIES',
  LANDLORD_REPORTS: 'LANDLORD_REPORTS',
  LANDLORD_SUBSCRIPTION: 'LANDLORD_SUBSCRIPTION',
  LANDLORD_SETTINGS: 'LANDLORD_SETTINGS',
} as const;

export type MenuCode = (typeof MENU_CODES)[keyof typeof MENU_CODES];
export const ALL_MENU_CODES: MenuCode[] = Object.values(MENU_CODES);
