export const PERMISSION_CODES = {
  PROPERTY_VIEW: 'PROPERTY_VIEW',
  PROPERTY_CREATE: 'PROPERTY_CREATE',
  PROPERTY_UPDATE: 'PROPERTY_UPDATE',
  PROPERTY_DELETE: 'PROPERTY_DELETE',
  UNIT_VIEW: 'UNIT_VIEW',
  UNIT_CREATE: 'UNIT_CREATE',
  UNIT_UPDATE: 'UNIT_UPDATE',
  UNIT_DELETE: 'UNIT_DELETE',
  TENANT_VIEW: 'TENANT_VIEW',
  TENANT_CREATE: 'TENANT_CREATE',
  TENANT_UPDATE: 'TENANT_UPDATE',
  TENANT_DELETE: 'TENANT_DELETE',
  LEASE_VIEW: 'LEASE_VIEW',
  LEASE_CREATE: 'LEASE_CREATE',
  LEASE_UPDATE: 'LEASE_UPDATE',
  LEASE_CLOSE: 'LEASE_CLOSE',
  PAYMENT_VIEW: 'PAYMENT_VIEW',
  PAYMENT_RECORD_MANUAL: 'PAYMENT_RECORD_MANUAL',
  ADDON_VIEW: 'ADDON_VIEW',
  ADDON_MANAGE: 'ADDON_MANAGE',
  UTILITY_READING_VIEW: 'UTILITY_READING_VIEW',
  UTILITY_READING_RECORD: 'UTILITY_READING_RECORD',
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',
  MEMBER_VIEW: 'MEMBER_VIEW',
  MEMBER_INVITE: 'MEMBER_INVITE',
  MEMBER_ROLE_UPDATE: 'MEMBER_ROLE_UPDATE',
} as const;

export type PermissionCode =
  (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];
export const ALL_PERMISSION_CODES: PermissionCode[] =
  Object.values(PERMISSION_CODES);
